# Generated by Django 4.1.7 on 2023-09-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('direccion', models.URLField(max_length=100)),
                ('fundation', models.DateField()),
                ('imagen', models.ImageField(upload_to='Company_Image')),
            ],
        ),
    ]
